version: '3.4'
services:
  sql_server:
    container_name: sql-movies-db
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    volumes:
      - movies-db-volume:/var/lib/mssqlql/data/
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password1*
volumes:
  movies-db-volume: null
